import type { InsertTemplate, FunnelStage } from "@shared/schema";

const createStages = (mainTitle: string, otoTitle: string, dsTitle: string): FunnelStage[] => [
  {
    id: "stage-1",
    title: mainTitle,
    type: "main" as const,
    hasVerse: true,
  },
  {
    id: "stage-2",
    title: otoTitle,
    type: "oto" as const,
    hasVerse: true,
  },
  {
    id: "stage-3",
    title: dsTitle,
    type: "ds" as const,
    hasVerse: true,
  },
];

export const TEMPLATE_SEEDS: InsertTemplate[] = [
  // CHURCH FUNDRAISING - 5 templates (premium_lite)
  {
    name: "Building Fund Campaign",
    description: "Raise funds for church building projects with scripture-backed giving appeals",
    category: "Church Fundraising",
    tier: "premium_lite",
    stages: createStages("Building Fund Main Offer", "Legacy Giving OTO", "Monthly Partner DS"),
    verse: { text: "Unless the Lord builds the house, the builders labor in vain.", reference: "Psalm 127:1", ctaText: "Build With Us" },
    theme: { primary: "#4F46E5", secondary: "#7C3AED", accent: "#EC4899" },
  },
  {
    name: "Mission Trip Fundraiser",
    description: "Fund mission trips with compelling faith-based appeals",
    category: "Church Fundraising",
    tier: "premium_lite",
    stages: createStages("Mission Trip Support", "Sponsor a Missionary OTO", "Prayer Partner DS"),
    verse: { text: "Go therefore and make disciples of all nations.", reference: "Matthew 28:19", ctaText: "Send Me" },
    theme: { primary: "#059669", secondary: "#10B981", accent: "#F59E0B" },
  },
  {
    name: "Youth Ministry Fund",
    description: "Support youth programs and summer camps",
    category: "Church Fundraising",
    tier: "premium_lite",
    stages: createStages("Youth Camp Fund", "Sponsor a Teen OTO", "Equipment Fund DS"),
    verse: { text: "Train up a child in the way he should go.", reference: "Proverbs 22:6", ctaText: "Invest in Youth" },
    theme: { primary: "#8B5CF6", secondary: "#A78BFA", accent: "#F472B6" },
  },
  {
    name: "Worship Equipment Drive",
    description: "Upgrade sound, lighting, and instruments for worship",
    category: "Church Fundraising",
    tier: "premium_lite",
    stages: createStages("Worship Tech Fund", "Premium Equipment OTO", "Basic Upgrade DS"),
    verse: { text: "Praise him with the strings and pipe!", reference: "Psalm 150:4", ctaText: "Enhance Worship" },
    theme: { primary: "#0891B2", secondary: "#22D3EE", accent: "#FB923C" },
  },
  {
    name: "Community Outreach Fund",
    description: "Support local community ministry and benevolence",
    category: "Church Fundraising",
    tier: "premium_lite",
    stages: createStages("Outreach Campaign", "Monthly Giving OTO", "One-Time Gift DS"),
    verse: { text: "Love your neighbor as yourself.", reference: "Mark 12:31", ctaText: "Give Now" },
    theme: { primary: "#DC2626", secondary: "#F87171", accent: "#FBBF24" },
  },

  // MINISTRY OUTREACH - 5 templates (premium_lite)
  {
    name: "Prison Ministry",
    description: "Reach inmates with the gospel and provide resources",
    category: "Ministry Outreach",
    tier: "premium_lite",
    stages: createStages("Prison Outreach Main", "Bible Distribution OTO", "Letter Writing DS"),
    verse: { text: "I was in prison and you came to visit me.", reference: "Matthew 25:36", ctaText: "Set Captives Free" },
    theme: { primary: "#475569", secondary: "#64748B", accent: "#F59E0B" },
  },
  {
    name: "Homeless Ministry",
    description: "Provide food, shelter, and hope to the homeless",
    category: "Ministry Outreach",
    tier: "premium_lite",
    stages: createStages("Feed the Hungry", "Shelter Support OTO", "Meal Sponsorship DS"),
    verse: { text: "For I was hungry and you gave me something to eat.", reference: "Matthew 25:35", ctaText: "Feed the Hungry" },
    theme: { primary: "#92400E", secondary: "#D97706", accent: "#84CC16" },
  },
  {
    name: "Hospital Chaplaincy",
    description: "Support hospital ministry and patient care",
    category: "Ministry Outreach",
    tier: "premium_lite",
    stages: createStages("Healing Ministry", "Chaplain Training OTO", "Prayer Support DS"),
    verse: { text: "Is anyone among you sick? Let them call the elders of the church.", reference: "James 5:14", ctaText: "Bring Healing" },
    theme: { primary: "#0284C7", secondary: "#38BDF8", accent: "#E11D48" },
  },
  {
    name: "Disaster Relief",
    description: "Emergency response ministry for natural disasters",
    category: "Ministry Outreach",
    tier: "premium_lite",
    stages: createStages("Emergency Response", "Rebuild Program OTO", "Supply Kit DS"),
    verse: { text: "The Lord is close to the brokenhearted.", reference: "Psalm 34:18", ctaText: "Bring Relief" },
    theme: { primary: "#B91C1C", secondary: "#EF4444", accent: "#3B82F6" },
  },
  {
    name: "Addiction Recovery",
    description: "Freedom from addiction through faith-based recovery",
    category: "Ministry Outreach",
    tier: "premium_lite",
    stages: createStages("Recovery Program", "Mentorship OTO", "Support Group DS"),
    verse: { text: "So if the Son sets you free, you will be free indeed.", reference: "John 8:36", ctaText: "Find Freedom" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#22C55E" },
  },

  // FAITH COACHING - 5 templates (premium_lite)
  {
    name: "Life Purpose Coaching",
    description: "Help clients discover their God-given purpose",
    category: "Faith Coaching",
    tier: "premium_lite",
    stages: createStages("Purpose Discovery", "Deep Dive Coaching OTO", "Self-Study Course DS"),
    verse: { text: "For we are God's handiwork, created in Christ Jesus to do good works.", reference: "Ephesians 2:10", ctaText: "Find Your Purpose" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#F472B6" },
  },
  {
    name: "Marriage Enrichment",
    description: "Strengthen marriages through biblical principles",
    category: "Faith Coaching",
    tier: "premium_lite",
    stages: createStages("Marriage Bootcamp", "Couples Retreat OTO", "Home Study DS"),
    verse: { text: "What God has joined together, let no one separate.", reference: "Mark 10:9", ctaText: "Strengthen Your Marriage" },
    theme: { primary: "#E11D48", secondary: "#FB7185", accent: "#FBBF24" },
  },
  {
    name: "Leadership Development",
    description: "Develop Christ-centered leaders for ministry and business",
    category: "Faith Coaching",
    tier: "premium_lite",
    stages: createStages("Leadership Foundations", "Executive Coaching OTO", "Team Training DS"),
    verse: { text: "But whoever would be great among you must be your servant.", reference: "Matthew 20:26", ctaText: "Lead Like Jesus" },
    theme: { primary: "#1D4ED8", secondary: "#3B82F6", accent: "#F59E0B" },
  },
  {
    name: "Financial Stewardship",
    description: "Biblical money management and debt freedom",
    category: "Faith Coaching",
    tier: "premium_lite",
    stages: createStages("Financial Freedom", "Wealth Building OTO", "Budget Basics DS"),
    verse: { text: "The borrower is slave to the lender.", reference: "Proverbs 22:7", ctaText: "Get Free" },
    theme: { primary: "#047857", secondary: "#10B981", accent: "#8B5CF6" },
  },
  {
    name: "Spiritual Growth",
    description: "Deepen faith and spiritual disciplines",
    category: "Faith Coaching",
    tier: "premium_lite",
    stages: createStages("Spiritual Disciplines", "Mentorship Program OTO", "Daily Devotional DS"),
    verse: { text: "But grow in the grace and knowledge of our Lord.", reference: "2 Peter 3:18", ctaText: "Grow Deeper" },
    theme: { primary: "#6366F1", secondary: "#818CF8", accent: "#EC4899" },
  },

  // BIBLE STUDY - 5 templates (premium_lite)
  {
    name: "Book-by-Book Study",
    description: "Deep dive into individual books of the Bible",
    category: "Bible Study",
    tier: "premium_lite",
    stages: createStages("Book Study Main", "Commentary Bundle OTO", "Study Guide DS"),
    verse: { text: "Your word is a lamp for my feet, a light on my path.", reference: "Psalm 119:105", ctaText: "Study the Word" },
    theme: { primary: "#854D0E", secondary: "#CA8A04", accent: "#2563EB" },
  },
  {
    name: "Women's Bible Study",
    description: "Engaging Bible studies designed for women",
    category: "Bible Study",
    tier: "premium_lite",
    stages: createStages("Women's Study", "Small Group Kit OTO", "Personal Study DS"),
    verse: { text: "She is clothed with strength and dignity.", reference: "Proverbs 31:25", ctaText: "Join the Study" },
    theme: { primary: "#DB2777", secondary: "#F472B6", accent: "#8B5CF6" },
  },
  {
    name: "Men's Bible Study",
    description: "Challenging Bible studies for men of faith",
    category: "Bible Study",
    tier: "premium_lite",
    stages: createStages("Men's Study", "Band of Brothers OTO", "Daily Reading DS"),
    verse: { text: "Be watchful, stand firm in the faith, act like men, be strong.", reference: "1 Corinthians 16:13", ctaText: "Man Up" },
    theme: { primary: "#1E40AF", secondary: "#3B82F6", accent: "#F97316" },
  },
  {
    name: "Couples Bible Study",
    description: "Studies designed for married couples",
    category: "Bible Study",
    tier: "premium_lite",
    stages: createStages("Couples Study", "Date Night Kit OTO", "Home Devotional DS"),
    verse: { text: "Two are better than one.", reference: "Ecclesiastes 4:9", ctaText: "Study Together" },
    theme: { primary: "#BE123C", secondary: "#F43F5E", accent: "#FBBF24" },
  },
  {
    name: "Youth Bible Study",
    description: "Engaging studies for teenagers and young adults",
    category: "Bible Study",
    tier: "premium_lite",
    stages: createStages("Teen Study", "Youth Leader Kit OTO", "Daily App DS"),
    verse: { text: "Don't let anyone look down on you because you are young.", reference: "1 Timothy 4:12", ctaText: "Get Started" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#22D3EE" },
  },

  // YOUTH MINISTRY - 5 templates (premium_lite)
  {
    name: "Summer Camp Registration",
    description: "Sign up youth for transformative summer experiences",
    category: "Youth Ministry",
    tier: "premium_lite",
    stages: createStages("Camp Registration", "VIP Experience OTO", "Day Camp DS"),
    verse: { text: "Remember your Creator in the days of your youth.", reference: "Ecclesiastes 12:1", ctaText: "Register Now" },
    theme: { primary: "#059669", secondary: "#34D399", accent: "#F59E0B" },
  },
  {
    name: "Youth Group Launch",
    description: "Launch or revitalize your youth ministry",
    category: "Youth Ministry",
    tier: "premium_lite",
    stages: createStages("Youth Group Kickoff", "Leader Training OTO", "Starter Kit DS"),
    verse: { text: "I have written to you, young people, because you are strong.", reference: "1 John 2:14", ctaText: "Launch Now" },
    theme: { primary: "#DC2626", secondary: "#F87171", accent: "#22C55E" },
  },
  {
    name: "Confirmation Class",
    description: "Prepare youth for church membership and commitment",
    category: "Youth Ministry",
    tier: "premium_lite",
    stages: createStages("Confirmation Program", "Family Package OTO", "Study Materials DS"),
    verse: { text: "Therefore go and make disciples of all nations, baptizing them.", reference: "Matthew 28:19", ctaText: "Confirm Your Faith" },
    theme: { primary: "#4F46E5", secondary: "#818CF8", accent: "#F472B6" },
  },
  {
    name: "Teen Retreat",
    description: "Life-changing weekend retreat for teenagers",
    category: "Youth Ministry",
    tier: "premium_lite",
    stages: createStages("Weekend Retreat", "Extended Stay OTO", "Day Pass DS"),
    verse: { text: "Come away by yourselves to a desolate place and rest a while.", reference: "Mark 6:31", ctaText: "Sign Up" },
    theme: { primary: "#0891B2", secondary: "#22D3EE", accent: "#F97316" },
  },
  {
    name: "Back to School",
    description: "Equip students for a faith-filled school year",
    category: "Youth Ministry",
    tier: "premium_lite",
    stages: createStages("School Year Prep", "Mentorship OTO", "Prayer Partner DS"),
    verse: { text: "The fear of the Lord is the beginning of knowledge.", reference: "Proverbs 1:7", ctaText: "Get Equipped" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#FBBF24" },
  },

  // ===== PREMIUM ONLY TEMPLATES (30 more) =====

  // WORSHIP MUSIC - 5 templates (premium only)
  {
    name: "Worship Album Launch",
    description: "Launch your worship album with a powerful funnel",
    category: "Worship Music",
    tier: "premium",
    stages: createStages("Album Pre-Order", "Deluxe Edition OTO", "Singles Bundle DS"),
    verse: { text: "Sing to the Lord a new song; sing to the Lord, all the earth.", reference: "Psalm 96:1", ctaText: "Pre-Order Now" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#F472B6" },
  },
  {
    name: "Worship Team Training",
    description: "Train your worship team for excellence",
    category: "Worship Music",
    tier: "premium",
    stages: createStages("Team Training", "Private Coaching OTO", "Video Course DS"),
    verse: { text: "Whatever you do, work at it with all your heart.", reference: "Colossians 3:23", ctaText: "Train Your Team" },
    theme: { primary: "#0891B2", secondary: "#22D3EE", accent: "#F59E0B" },
  },
  {
    name: "Choir Recruitment",
    description: "Build your church choir with passionate singers",
    category: "Worship Music",
    tier: "premium",
    stages: createStages("Join the Choir", "Voice Training OTO", "Sheet Music DS"),
    verse: { text: "Speak to one another with psalms, hymns, and songs.", reference: "Ephesians 5:19", ctaText: "Join Us" },
    theme: { primary: "#DC2626", secondary: "#F87171", accent: "#22C55E" },
  },
  {
    name: "Songwriter Mentorship",
    description: "Develop worship songwriters in your church",
    category: "Worship Music",
    tier: "premium",
    stages: createStages("Songwriter Course", "1-on-1 Mentoring OTO", "Resource Library DS"),
    verse: { text: "He put a new song in my mouth, a hymn of praise.", reference: "Psalm 40:3", ctaText: "Write New Songs" },
    theme: { primary: "#6366F1", secondary: "#818CF8", accent: "#EC4899" },
  },
  {
    name: "Worship Night Event",
    description: "Host a powerful night of worship and prayer",
    category: "Worship Music",
    tier: "premium",
    stages: createStages("Worship Night Tickets", "VIP Experience OTO", "Livestream DS"),
    verse: { text: "Enter his gates with thanksgiving and his courts with praise.", reference: "Psalm 100:4", ctaText: "Get Tickets" },
    theme: { primary: "#7C2D12", secondary: "#EA580C", accent: "#FBBF24" },
  },

  // MISSIONS & EVANGELISM - 5 templates (premium only)
  {
    name: "Short-Term Missions",
    description: "Recruit and fund short-term mission trips",
    category: "Missions & Evangelism",
    tier: "premium",
    stages: createStages("Mission Trip Info", "Full Sponsorship OTO", "Prayer Partner DS"),
    verse: { text: "The harvest is plentiful, but the workers are few.", reference: "Matthew 9:37", ctaText: "Join the Mission" },
    theme: { primary: "#059669", secondary: "#10B981", accent: "#F59E0B" },
  },
  {
    name: "Evangelism Training",
    description: "Equip believers to share their faith confidently",
    category: "Missions & Evangelism",
    tier: "premium",
    stages: createStages("Evangelism Course", "Certification OTO", "Basic Training DS"),
    verse: { text: "Always be prepared to give an answer to everyone who asks.", reference: "1 Peter 3:15", ctaText: "Get Trained" },
    theme: { primary: "#B91C1C", secondary: "#EF4444", accent: "#3B82F6" },
  },
  {
    name: "Church Planting",
    description: "Support and launch new church plants",
    category: "Missions & Evangelism",
    tier: "premium",
    stages: createStages("Church Plant Support", "Founding Member OTO", "Prayer Team DS"),
    verse: { text: "I will build my church, and the gates of hell shall not prevail.", reference: "Matthew 16:18", ctaText: "Plant a Church" },
    theme: { primary: "#4F46E5", secondary: "#6366F1", accent: "#EC4899" },
  },
  {
    name: "Unreached People Groups",
    description: "Reach the unreached with the gospel",
    category: "Missions & Evangelism",
    tier: "premium",
    stages: createStages("Adopt a People Group", "Long-Term Support OTO", "Monthly Giving DS"),
    verse: { text: "This gospel of the kingdom will be preached in the whole world.", reference: "Matthew 24:14", ctaText: "Reach the Unreached" },
    theme: { primary: "#0F766E", secondary: "#14B8A6", accent: "#F97316" },
  },
  {
    name: "Street Evangelism",
    description: "Take the gospel to the streets",
    category: "Missions & Evangelism",
    tier: "premium",
    stages: createStages("Street Team Training", "Leadership Track OTO", "Tract Pack DS"),
    verse: { text: "Go out to the roads and country lanes and compel them to come in.", reference: "Luke 14:23", ctaText: "Hit the Streets" },
    theme: { primary: "#DC2626", secondary: "#F87171", accent: "#FBBF24" },
  },

  // CHRISTIAN AUTHORS - 5 templates (premium only)
  {
    name: "Book Launch Funnel",
    description: "Launch your Christian book with maximum impact",
    category: "Christian Authors",
    tier: "premium",
    stages: createStages("Book Pre-Order", "Signed Edition OTO", "eBook Only DS"),
    verse: { text: "Of making many books there is no end.", reference: "Ecclesiastes 12:12", ctaText: "Pre-Order Now" },
    theme: { primary: "#6366F1", secondary: "#818CF8", accent: "#F472B6" },
  },
  {
    name: "Devotional Series",
    description: "Sell your daily devotional series",
    category: "Christian Authors",
    tier: "premium",
    stages: createStages("Devotional Bundle", "Year-Long Set OTO", "Single Month DS"),
    verse: { text: "Your word I have hidden in my heart.", reference: "Psalm 119:11", ctaText: "Start Your Journey" },
    theme: { primary: "#854D0E", secondary: "#CA8A04", accent: "#7C3AED" },
  },
  {
    name: "Bible Study Guide",
    description: "Market your Bible study curriculum",
    category: "Christian Authors",
    tier: "premium",
    stages: createStages("Study Guide Main", "Leader Kit OTO", "Student Edition DS"),
    verse: { text: "Study to shew thyself approved unto God.", reference: "2 Timothy 2:15", ctaText: "Get the Guide" },
    theme: { primary: "#0891B2", secondary: "#22D3EE", accent: "#F59E0B" },
  },
  {
    name: "Children's Book",
    description: "Sell your faith-based children's books",
    category: "Christian Authors",
    tier: "premium",
    stages: createStages("Children's Book", "Complete Series OTO", "Coloring Book DS"),
    verse: { text: "Let the little children come to me.", reference: "Matthew 19:14", ctaText: "Order Now" },
    theme: { primary: "#DB2777", secondary: "#F472B6", accent: "#22C55E" },
  },
  {
    name: "Memoir/Testimony",
    description: "Share your testimony and transformation story",
    category: "Christian Authors",
    tier: "premium",
    stages: createStages("My Story Book", "Speaking Package OTO", "Digital Edition DS"),
    verse: { text: "They triumphed over him by the blood of the Lamb and by the word of their testimony.", reference: "Revelation 12:11", ctaText: "Read My Story" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#FBBF24" },
  },

  // RETREAT & EVENTS - 5 templates (premium only)
  {
    name: "Women's Retreat",
    description: "Host a transformative women's retreat",
    category: "Retreat & Events",
    tier: "premium",
    stages: createStages("Retreat Registration", "VIP Package OTO", "Day Pass DS"),
    verse: { text: "Be still, and know that I am God.", reference: "Psalm 46:10", ctaText: "Register Now" },
    theme: { primary: "#DB2777", secondary: "#F472B6", accent: "#8B5CF6" },
  },
  {
    name: "Men's Retreat",
    description: "Challenge men to grow in faith and leadership",
    category: "Retreat & Events",
    tier: "premium",
    stages: createStages("Men's Retreat", "Adventure Package OTO", "Basic Registration DS"),
    verse: { text: "Iron sharpens iron, and one man sharpens another.", reference: "Proverbs 27:17", ctaText: "Join the Men" },
    theme: { primary: "#1E40AF", secondary: "#3B82F6", accent: "#F97316" },
  },
  {
    name: "Marriage Conference",
    description: "Strengthen marriages through a powerful conference",
    category: "Retreat & Events",
    tier: "premium",
    stages: createStages("Conference Tickets", "Couples Getaway OTO", "Virtual Access DS"),
    verse: { text: "And the two will become one flesh.", reference: "Ephesians 5:31", ctaText: "Save Your Spot" },
    theme: { primary: "#BE123C", secondary: "#F43F5E", accent: "#FBBF24" },
  },
  {
    name: "Leadership Summit",
    description: "Gather and equip church leaders",
    category: "Retreat & Events",
    tier: "premium",
    stages: createStages("Summit Registration", "Executive Track OTO", "Basic Pass DS"),
    verse: { text: "Where there is no vision, the people perish.", reference: "Proverbs 29:18", ctaText: "Lead with Vision" },
    theme: { primary: "#4F46E5", secondary: "#6366F1", accent: "#10B981" },
  },
  {
    name: "Family Camp",
    description: "Create lasting memories with family camp",
    category: "Retreat & Events",
    tier: "premium",
    stages: createStages("Family Camp Registration", "Extended Stay OTO", "Day Activities DS"),
    verse: { text: "As for me and my house, we will serve the Lord.", reference: "Joshua 24:15", ctaText: "Register Your Family" },
    theme: { primary: "#059669", secondary: "#34D399", accent: "#F472B6" },
  },

  // PASTORAL COUNSELING - 5 templates (premium only)
  {
    name: "Grief Support",
    description: "Help families through loss and grief",
    category: "Pastoral Counseling",
    tier: "premium",
    stages: createStages("Grief Support Group", "Private Sessions OTO", "Workbook DS"),
    verse: { text: "Blessed are those who mourn, for they will be comforted.", reference: "Matthew 5:4", ctaText: "Find Comfort" },
    theme: { primary: "#475569", secondary: "#64748B", accent: "#A78BFA" },
  },
  {
    name: "Pre-Marriage Counseling",
    description: "Prepare couples for a Christ-centered marriage",
    category: "Pastoral Counseling",
    tier: "premium",
    stages: createStages("Pre-Marriage Course", "Intensive Weekend OTO", "DIY Workbook DS"),
    verse: { text: "He who finds a wife finds a good thing.", reference: "Proverbs 18:22", ctaText: "Prepare for Marriage" },
    theme: { primary: "#E11D48", secondary: "#FB7185", accent: "#FBBF24" },
  },
  {
    name: "Crisis Intervention",
    description: "Emergency pastoral care for those in crisis",
    category: "Pastoral Counseling",
    tier: "premium",
    stages: createStages("Crisis Support", "Ongoing Care OTO", "Hotline Access DS"),
    verse: { text: "God is our refuge and strength, an ever-present help in trouble.", reference: "Psalm 46:1", ctaText: "Get Help Now" },
    theme: { primary: "#B91C1C", secondary: "#EF4444", accent: "#3B82F6" },
  },
  {
    name: "Family Counseling",
    description: "Restore and strengthen family relationships",
    category: "Pastoral Counseling",
    tier: "premium",
    stages: createStages("Family Sessions", "Intensive Program OTO", "Parent Guide DS"),
    verse: { text: "Children are a heritage from the Lord.", reference: "Psalm 127:3", ctaText: "Heal Your Family" },
    theme: { primary: "#0891B2", secondary: "#22D3EE", accent: "#F472B6" },
  },
  {
    name: "Addiction Counseling",
    description: "Faith-based recovery and freedom from addiction",
    category: "Pastoral Counseling",
    tier: "premium",
    stages: createStages("Recovery Program", "Residential Care OTO", "Support Group DS"),
    verse: { text: "He sent out his word and healed them.", reference: "Psalm 107:20", ctaText: "Start Recovery" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#22C55E" },
  },

  // CHRISTIAN EDUCATION - 5 templates (premium only)
  {
    name: "Homeschool Curriculum",
    description: "Faith-based homeschool curriculum and resources",
    category: "Christian Education",
    tier: "premium",
    stages: createStages("Curriculum Package", "Full Year Bundle OTO", "Single Subject DS"),
    verse: { text: "Train up a child in the way he should go.", reference: "Proverbs 22:6", ctaText: "Start Homeschooling" },
    theme: { primary: "#059669", secondary: "#10B981", accent: "#F59E0B" },
  },
  {
    name: "Sunday School",
    description: "Complete Sunday School curriculum and materials",
    category: "Christian Education",
    tier: "premium",
    stages: createStages("Curriculum Access", "Teacher Training OTO", "Activity Pack DS"),
    verse: { text: "Jesus said, 'Let the little children come to me.'", reference: "Matthew 19:14", ctaText: "Get Curriculum" },
    theme: { primary: "#DC2626", secondary: "#F87171", accent: "#3B82F6" },
  },
  {
    name: "VBS Package",
    description: "Complete Vacation Bible School program",
    category: "Christian Education",
    tier: "premium",
    stages: createStages("VBS Main Package", "Deluxe Kit OTO", "Digital Only DS"),
    verse: { text: "Teach them to your children, talking about them when you sit at home.", reference: "Deuteronomy 11:19", ctaText: "Plan Your VBS" },
    theme: { primary: "#7C3AED", secondary: "#A78BFA", accent: "#FBBF24" },
  },
  {
    name: "Seminary Course",
    description: "Online seminary and theological education",
    category: "Christian Education",
    tier: "premium",
    stages: createStages("Course Enrollment", "Degree Program OTO", "Certificate Track DS"),
    verse: { text: "Study to show yourself approved unto God.", reference: "2 Timothy 2:15", ctaText: "Enroll Now" },
    theme: { primary: "#1E40AF", secondary: "#3B82F6", accent: "#10B981" },
  },
  {
    name: "Discipleship Program",
    description: "Comprehensive discipleship training program",
    category: "Christian Education",
    tier: "premium",
    stages: createStages("Discipleship Course", "Mentorship Track OTO", "Self-Study DS"),
    verse: { text: "Go therefore and make disciples of all nations.", reference: "Matthew 28:19", ctaText: "Become a Disciple" },
    theme: { primary: "#6366F1", secondary: "#818CF8", accent: "#EC4899" },
  },
];
